/// Flutter icons Icons2
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons2
///      fonts:
///       - asset: fonts/Icons2.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icons2 {
  Icons2._();

  static const _kFontFam = 'Icons2';
  static const String? _kFontPkg = null;

  static const IconData bath_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData SecurityCam = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData AC = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pool = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balcony = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Wardrobe = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData actions_calendar_month = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData actions_heart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_arrow_backward = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communication_call = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communication_chat_outlined = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_group_equal = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_user = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office_table = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmlid_226 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bath = IconData(0xf2cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
