// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSDzFzZ3IuTZBjsruMqoRZ6pkFDNiRRM',
    appId: '1:176986571063:android:fc5aaf33284efd3b6e9ab2',
    messagingSenderId: '176986571063',
    projectId: 'msknapp',
    storageBucket: 'msknapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKTAl0ANkImTI2KRj3uhgaEV80AmmEUg',
    appId: '1:176986571063:ios:129ec1dbe41199606e9ab2',
    messagingSenderId: '176986571063',
    projectId: 'msknapp',
    storageBucket: 'msknapp.appspot.com',
    androidClientId: '176986571063-44ri4jdtjctbk2frisinkkf8irjf3rum.apps.googleusercontent.com',
    iosClientId: '176986571063-0qpksr42egn0em94stlgl6b1o7s7terl.apps.googleusercontent.com',
    iosBundleId: 'com.example.maskkn',
  );
}
